### ISSUE TITLE
No syntax highlighting in `jldoctest` block

### ISSUE THREAD

**Issue by dpsanders** [JuliaDocs/Documenter.jl#385]
I seem to get syntax highlighting in code blocks with `julia` but not with `jldoctest`.

**Comment by MichaelHatherly** [comment]
Thanks. Should be fixed by the referenced commit.

**Comment by TotalVerb** [comment]
I still don't see syntax highlighting in `jldoctest` blocks; this is also the case in the Base manual. Note the lack of highlighting in these blocks: https://docs.julialang.org/en/latest/manual/strings.html#String-Basics-1

**Comment by mortenpi** [comment]
I don't think highlight.js support highlighting doctests, so the `language-jldoctest` class doesn't really do anything.

**Comment by mortenpi** [comment]
Should be fixed by #486.
